apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: imgautomate
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: poddemo
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: bhaveshbhagat724@gmail.com
        name: BhaveshBhagat
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
      signingKey:
        secretRef:
          name: pgp-public
    push:
      branch: master
  update:
    path: ./kustomize
    strategy: Setters
---
apiVersion: v1
kind: Secret
metadata:
  name: gittoken
  namespace: flux-system
stringData:
  git.asc: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----

    lQPGBGU6bhEBCAC0r/a5o46u1FPaqcYneV2diqzBujulQiDR3yWyI33AV2bQCYAs
    ujlAAgraL94VUWTqsQisLDrpknwtW4bkITL9qIu6NkABeEy5sFP0g7fF2UmuAHv2
    ZyyBXfo78axzqaqPn2Olm+NIG7g0FDYyUqdFhJY2ZYlw8HfukZEpWSDsQW/JLk8H
    sfLHVnELppJ+ulhDZ864ncaWyLBVd9xx5t3qWBixjIcfU9lwZmP0gXWrvATV/M4T
    lBDaPabzVWhwztklE6McHqpDGzM7/msBSKjauOR1swRn1TvrLSfG19X1tI03uiGW
    aMcj6DY8k9vGJooXunD3z8y+0iRQebrMjy/vABEBAAH+BwMCh/w8+xTUuGPtz/tG
    mJFJAVONJre4hsXlpYRhg91kbGhdGHhq8il98XMci3sw+8lFroVtBNupvzbZ1jTn
    rQUsNghARl1eVsqzHKp1HOSxDRG1oImgN1H9sQgt3a5p17PD6LEQMwWAZbUKUzGz
    5fO4tanw/fBoYW6KHD6lWzIak2Y27jPQYiihJnXQJIYYL690+7bEeJcu/9RQZIT7
    +ytb33SW5L1rIggL/D7C6edyQy5lwvm3rUIRZjoMa9gj42Oc6azIS7X1L6wFdGLK
    b/xILKPyA/wgXG/8ecDcxmwilGSfatZ643d2vK4KQNYwmFDqUZJGKLO9iXGGQQdU
    GIgNDVUtJOCLGpi6NyMJIt2Rl/i5+a7hzq1ui48W+mwWHCHd+LroN/0D7TSDZnMa
    c0LDQiihaWKDBQ09llRE4R3Rq7fFuP0lepVcug5nZ7zHEZAOQ+/tj6bAeoctoBKt
    5BEoz+k/jGA6uIMYSiQjV5zMrP9i/F0LKPmw3hVWN2y+LV3dKylJ4qmzZ0l7WKBL
    yGXegUfZcYwy5z1vbFcCXMIPUAqqUBxcX0EiPCuIOq6gCg2R+kCd2u6TXuP2dnCM
    BGLmLNj7KY4B0NMEX8nS0imxHrf/lJnIyC2wqWndof4T/BuFMzEj5Nvs1Lu6/IvM
    Qmda6JGSHMxRJv99GPoRbZDoOCP9oMlrczhDrKo75nHaw9jetVZr0WwltiI7i3kh
    /j0CTYBOApo2E4qXumOOsu1M/bF4TDWYKsLQD1z4amvbaMbOABbNzNcTDQzwD6Nd
    AYoc6/q04qqPt/kt7Y1KXnjWK/hcTjFnWjzyygu9HZ4wzhLrRAiPmV0esmW88d9b
    wlOiZYTFVZkz67OD6bFr3LiegelfJcq4hr368H8nW714/sxgIj5l38NchVLATNqd
    jGvgkNW4SmBDtCxCaGF2ZXNoIChoZWxsbykgPGJoYXZlc2hiaGFnYXQ3MjRAZ21h
    aWwuY29tPokBTgQTAQgAOBYhBDFeHd5HsaT5xRhzhmXcbaBkn5AgBQJlOm4RAhsD
    BQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEGXcbaBkn5Ag1pIH/3V2Sp0n1jj1
    cT11Ln0LOZ3FzqnEMdxaG5SDxoH1HMSps9e2lUtcE+bZbm8UH0FEn0UQCD1Toy48
    RkwrRLB/kCAkOQgD7W+e3lH2ad+ohXialjjqbOsf9FBUQIBk5pomZ3UKz83CYiyf
    NnvEigx6wq9I1M+IMyUkGC478cIW/lF/BUisBMHljoOHxSvEI3V8dVdhNyKQqOjE
    G194baWhbiJMqvCx4kxrvRccCPFq2hrG04bf6PGJifF2BaKdEH/GeWmFsaoxOnxy
    TwxYpf162lCFDbgct6atoehPQB7Vvt/Kt+ssEZJKO1wUmGdtEnAqt3QCh+Am1WX0
    VI8LMI3zX2ydA8YEZTpuEQEIANa3Lrha3j0pgDT4VQ1mGjOTyJ+ProuLOzImSs5Y
    B0s1kf3otsNC5xvbnqhQ7cawiVIExrSV4/uSTSBYgFZvjoHZSD3vzst5+Q621klY
    uQxlFx+Wp4bgZHhcuVzRxelspCafteuUcei7PjMU764Ijs7prqHHMyzKRMJu4NMP
    wAhHEFxe0qIcd2p+b1z9wjW2IO3YCvqjhEexHbfYYTjBuLa0YADGwkLXDwuLYx1W
    L4fVBxisz074KdbYHstfq/auESccjaIOG+y9Z6ID3QJvDQApt9YIAcFi69w14CZ1
    IdmnXbZ8ouoqSCLPLVZN9OvK41iY8d1Q49HxCvm8KLtCY7UAEQEAAf4HAwLfNdak
    mrIra+1qc6nc6ecSGvTdxKu8xAOJA7TvWTLSyYjlOpiMNAjIMbLfPPsiOJbAmFPM
    n7h/fvy05vdvs8IS8VJUiZl2aGuxH29hsnK3yefUxofGoLbvpSB3Vu7zs/ZnO0cq
    H1lsPkEF807RRGt3j6xKbPaWfQUlaYoFHjZ53dH4em7Af4Oujofigd7JfXl1Ni1C
    AkeoGJ4xcXWf8gKYnMnyyW2mpbZzldcGTUaVFq4ROg7aKiWRzpA7Zu2PzQw0Hy7t
    kuIuhudeEJ4EhD/9AaxwZtsM1NeqStigJfxzQtzpwNNInH9A1NEg4XTTBrAWKCXW
    yARSm3x7Q/julb3e92z7OHzpRH4+cKPF6sQi1x4qlO5UQBrXHzspBn6Xyxo5WYAC
    iSXmNlyZRWEW8SPO/HyobtU6hTDb0P96rERd6cHPaQk2YOEm9kJ6HI1gvpr28tUe
    t9XwkBFSHg6PmIaTz4KL+6vY3p2pPShlHWL49144ZEm6BD7IYn4YANGUE6yNoP4/
    wr13kYfE3i3mt6vHuDCVNckWpIm0yE5T70ELV+e0d8FLRu6aUzwq8VT9lleAKsHW
    W8TcB38ioaek0N25vqefsNqLVt+ib9jtQgwKRyxs+l2F5UCksCB/mdXY89cclIxm
    4RH5tKoS99MUSoNG/vh1DWHuuju4R1mKElWzS9PLjqRJM24o1s/LHOAi4xD/lFmv
    FnKseDdUZ6GIlBlmnRhGDpn/I6jN5J2GXjIfWmIi2ip3Ubb2DdHE0G3qjsOfa50P
    ByEC+eG4PLp5hrmBliVvN5AZgtgCLR+dBbhNBtqnDbbeKxa9MJBLzM99fi4GgaCp
    EjeOS6ZeTKwJZ2NCvINSIZZvlsauZfIDzsvQzxMdPSoNeL0Ssgtf/8uYcuzlkZtp
    31gvsAlaSNy6FsN2hK0n3U2JATYEGAEIACAWIQQxXh3eR7Gk+cUYc4Zl3G2gZJ+Q
    IAUCZTpuEQIbDAAKCRBl3G2gZJ+QIHEGCACd4vdJwU5I1l9E+3PHtNYChirxY5vJ
    vLB3epatx9Bq2r9/irIRKGOpaXi7zWgdn/zPxX7iKblc9QHz58m3yp5nRE1gNf6X
    kE0HZjXcTRNdybS5Uzqeeu58trRiviRJGPgV0aCY+hCcrE1nuc49pgO3Dbvup+QJ
    ehKJUPCGyA3T+lfcO7ezMY+OpSDjbwcwRNIrdnUHXyf+7J9eLGD81drfJjfEnp7h
    1ojUlaeLzAgKQQy9EyORooPLPukzB35icr+8Tni5Xdmbf5prT4gdF6hkDl/2OlPp
    qdCYiTPPw3CMZ4EFlt8x6C+ZEDKWZq+2Zmu/K6UlXE4EfljIeMjc8Wr+
    =nOuA
    -----END PGP PRIVATE KEY BLOCK-----
  # passphrase: Radisys@10


        	
